### ISSUE TITLE
Round Bracket Comment Lines

### ISSUE THREAD

**Issue by sonofeft** [zaxe3d/gcode_analyzer#1]
I was playing with your code, but it failed on my ReplicatorG GCODE due to the ReplicatorG using the "round bracket" form for comments. (see: http://reprap.org/wiki/G-code#Comments)

I put together a quick workaround by changing your file reading code from:
line = fp.readline()
to:
line = standardize_comments( fp.readline() )

Where the function "standardize_comments" will reformat the input line to convert paren comments into semicolon comments.

As a starting point, I'm showing my code below, however, you may want to modify/refactor the whole thing.

def find_matching_parens( text ):
    '''Return a dictionary of matching parens'''
    istart = []  # stack of indices of opening parentheses
    D = {}

    for i, c in enumerate(text):
        if c == '(':
             istart.append(i)
        if c == ')':
            try:
                D[istart.pop()] = i
            except IndexError:
                print 'WARNING... Too many closing parentheses'
    if istart:  # check if stack is empty afterwards
        print 'WARNING...Too many opening parentheses'
        
    return D

def standardize_comments( line ):
    '''
    convert "(...)" style comments int ";" style comments.
    '''
    # if there are no "(...)" style comments, don't worry about it.
    if line.count('(')==0:
        return line
    
    codeL = [] # list of strings to be joined and returned
    
    commentL = [] # comments to be added after trailing ";" character
    if line.find(';') >= 0:
        line, comment = line.split(';',1)
        commentL.append( comment )
    
    while line.find('(') >= 0:
        istart = line.find('(')
        D = find_matching_parens( line )
        if istart in D:
            iend = D[istart]
        else:
            iend = len(line)-1
            print 'WARNING, No matching ending perenthesis in line. "%s"'%line.strip()
            
        codeL.append( line[:istart+1][:-1] )
        commentL.append( line[istart:iend]+')' ) # preserve parens as clue to comment style
        line = line[iend+1:]
        
    codeL.append( line )
    
    return ''.join(codeL) + ';' + ''.join(commentL)

**Comment by cangelis** [comment]
Just pushed a fix. Can you please review?

**Comment by sonofeft** [comment]
Your regular expression approach worked on my sample case and gave the same answer as my long-winded solution.

=========== My output ============
WARNING...Too many opening parentheses
WARNING, No matching ending perenthesis in line. "G162 X Y F2500 (home XY axes maximum"
seconds     = 363.316263539
time        = 0:06:03.316264
filament    = 384.538 mm  =  15.1393 in

============== Your new regular expression output ===========
seconds     = 363.316263539
time        = 0:06:03.316264
filament    = 384.538 mm  =  15.1393 in
